#!/usr/bin/env python
# coding: utf-8

# In[1]:


# csv standardization
import os
import sys


# In[2]:


if(len(sys.argv) != 3):
    sys.exit('Usage: <directory of organised data pebl data> <userID>\nChanges the name of the csv according to the subject ID')


# In[19]:


directory = sys.argv[1]
userID = sys.argv[2]
# directory = '.'
# userID = '1'
try:
    os.chdir(directory+'/'+userID)
except:
    sys.exit('no such file or directory')


# In[12]:


list_of_csv = next(os.walk(os.getcwd()))[2]
#if(len(list_of_csv)!=1):
#    sys.exit('wrong directory')


# In[14]:


test_name,number_extension = list_of_csv[0].split('-')


# In[16]:


number,extension = number_extension.split('.')


# In[17]:


new_name = test_name+'-'+userID+'.'+extension


# In[18]:


os.rename(list_of_csv[0],new_name)

