#!/usr/bin/env python
import sys
import numpy as np
import os
import csv
import classifications as clf
#usage
def usage():
    sys.exit('Usage: \nInput: <base_directory> \n outputs a entry into OUTPUT.csv <SubjID> <aasanaID> <metric_name> <Metric_value>')
if(len(sys.argv) != 2):
    usage()
#filename = 'version2/Kunal_Naukasana/joints.csv'
# subjID = ''

directory = sys.argv[1]
# starttime = np.float64(sys.argv[2])
# duration = np.float64(sys.argv[3])
# subjectID = sys.argv[4]
# aasanaID = sys.argv[5]
# subject_name = ''

output_dir = os.getcwd()
os.chdir(directory)
list_of_subjects = next(os.walk(os.getcwd()))[1]

# aasana_start_dur['someasana'] = [left start time, left duration, right start time, right duration]
aasana_start_dur = {
    'ArdhaChakrasana':[25,60,25,60], # non bilateral
    'Garudasana':[25,25,65,25],
    'Gorakshasana':[25,60,25,60], # non bilateral          
    'Katichakrasana':[25,60,100,60], 
    'Natarajasana':[25,40,80,40],
    'Natavarasana':[25,60,100,60],
    'Naukasana':[15,20,15,20], # non bilateral
    'Padahastasana':[30,90,30,90], # non bilateral
    'ParivrittaTrikonasana':[30,30,80,30], 
    'Pranamasana':[25,30,65,30],
    'Santolanasana':[25,35,25,35], # non bilateral
    'Still':[20,20,20,20], # non bilateral
    'Tadasana':[25,55,25,55], # non bilateral
    'TiryakTadasana':[25,35,75,35],
    'Trikonasana':[30,30,80,30],
    'Tuladandsana':[20,20,20,20], # needs input
    'Utkatasana':[20,30,20,30], # non bilateral
    'Virabhadrasana':[30,25,70,25],
    'Vrikshasana':[25,30,65,30],    
}

joint_types = ['JointType_SpineBase',
               'JointType_SpineMid',
               'JointType_Neck',
               'JointType_Head',
               'JointType_ShoulderLeft',
               'JointType_ElbowLeft',
               'JointType_WristLeft',
               'JointType_HandLeft',
               'JointType_ShoulderRight',
               'JointType_ElbowRight',
               'JointType_WristRight',
               'JointType_HandRight',
               'JointType_HipLeft',
               'JointType_KneeLeft',
               'JointType_AnkleLeft',
               'JointType_FootLeft',
               'JointType_HipRight',
               'JointType_KneeRight',
               'JointType_AnkleRight',
               'JointType_FootRight',
               'JointType_SpineShoulder',
               'JointType_HandTipLeft',
               'JointType_ThumbLeft',
               'JointType_HandTipRight',
               'JointType_ThumbRight'
               ]

def getIndices(h,m,s,jointwise):
    #binary search for finding index
    timestring = 0
    lb = 0
    ub = len(jointwise[1])
    mid = int((lb+ub)/2)
    while(lb<ub):
        timestring = jointwise[0][mid][1]
        jh,jm,js = timestring.split(':')
        jh,jm,js = np.float64(jh),np.float64(jm),np.float64(js)
        compare = 3600*(jh-h)+60*(jm-m)+(js-s)
        if(compare>0): #it means data[mid] is greater than item
            ub = mid-1
        elif(compare<0):
            lb = mid+1
        else:
            return mid
        mid = int((lb+ub)/2)
    return mid

# returns a tuple of begin, end
def getBegEnd(start,duration,jointwise):
    sh = int(start/3600)
    sm = int((start%3600)/60)
    ss = (start%60)
    dh = int(duration/3600)
    dm = int((duration%3600)/60)
    ds = (duration%60)
    initial = jointwise[0][0][1]
    Ih,Im,Is = initial.split(':')
    Ih,Im,Is = np.float64(Ih),np.float64(Im),np.float64(Is)
    #commencement of holding aasana
    cs = (Is + ss)%60
    cm = int((Is+ss)/60) + Im + sm
    ch = Ih + sh + int(cm/60)
    cm = cm%60
    #end of holding aasana
    es = cs + ds
    em = int(es/60) + cm + dm
    es = es%60
    eh = int(em/60) + ch + dh
    em = em%60
    #get indices
    begin = getIndices(ch,cm,cs,jointwise)
    end = getIndices(eh,em,es,jointwise)
    return begin,end
        
def extract_classification_stability(subjID,aasana_list,group_name):
	stabilities_l = []
	stabilities_r = []
	mean_l = 0
	mean_r = 0
	mean = 0

	with open('OUTPUT.csv','r') as csvFile:
		csv_reader = csv.reader(csvFile)
		for row in csv_reader:
			if(not row):
				continue
			if(row[1] in aasana_list and row[0] == subjID):
				if(row[2]=='Stability-l'):
					stabilities_l.append(np.float64(row[3]))
				elif(row[1]=='Stability-r'):
					stabilities_r.append(np.float64(row[3]))
	mean_l = np.mean(stabilities_l)
	mean_r = np.mean(stabilities_r)
	mean = (mean_l + mean_r)/2
	row1 = [subjID,group_name,'Stability-l',mean_l]
	row2 = [subjID,group_name,'Stability-r',mean_r]
	row3 = [subjID,group_name,'Stability',mean]
	rows = [row1,row2,row3]
	with open('OUTPUT.csv','a') as csvFile:
		csv_writer = csv.writer(csvFile)
		for row in rows:
			csv_writer.writerow(row) 



for subjectID in list_of_subjects:

    list_of_aasanas = next(os.walk(os.getcwd()+'/'+subjectID))[1]
    # obtain a list of aasanas using the names of the folders in the directory
    # generate a list of names of the folders in the directory
    # extract the aasana name from that list
    for i in range(len(list_of_aasanas)):
        temp = list_of_aasanas[i].split('_')
        aasana1 = ''
        for j in range(1,len(temp)):
            aasana1 = aasana1+temp[j]
        list_of_aasanas[i] = aasana1
    
    # generate a list of joints by accessing the files in list_of_aasanas
    for aasanaID in list_of_aasanas:
        filename = directory+'/'+subjectID+'/'+subjectID+'_'+aasanaID+'/joints.csv'
        # filename = sys.argv[1]
        joints = []
        with open(filename, 'r') as fo:
            csv_reader = csv.reader(fo)
            i = 0
            for row in csv_reader:
                if(i%2 == 0):
                    joints.append(row) 
                i = i+1

    
        weights = np.zeros((len(joint_types),3),dtype = np.float64)
        weights = weights + 1

        jointwise = [[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]
        for row in joints:
            for j in range(len(joint_types)):
                if(row[2]==joint_types[j]):
                    jointwise[j].append(row)
    	# jointwise[j] contains data on joint joint_types[j]
        # get begin and end
        time_data = aasana_start_dur[aasanaID]
        start_left = int(time_data[0])
        dur_left = int(time_data[1])
        start_right = int(time_data[2])
        dur_right = int(time_data[3])

        begin_left,end_left = getBegEnd(start_left,dur_left,jointwise)
        begin_right,end_right = getBegEnd(start_right,dur_right,jointwise)
        # print(jointwise[0][begin][1])
        # print(jointwise[0][end][1])
        instability = []

        # create left hand side data
        for i in range(25):
            any_joint = jointwise[i]
            hrs = []
            mns = []
            scs = []
            x = []
            y = []
            z = []
            varX = []
            varY = []
            varZ = []
            inverted_frame_rate = []
            for row in any_joint[begin_left+10:end_left-10]:
                hours, minutes, seconds = row[1].split(':')
                hours, minutes, seconds = np.float64(hours), np.float64(minutes), np.float64(seconds) 
                hrs.append(hours)
                mns.append(minutes)
                scs.append(seconds)
                x.append(np.float64(row[7]))
                y.append(np.float64(row[8]))
                z.append(np.float64(row[9]))
            mx,my,mz = np.mean(x),np.mean(y),np.mean(z)
            for i in range(1,len(x)):
                inverted_frame_rate.append(3600*(hrs[i]-hrs[i-1])+60*(mns[i]-mns[i-1])+(scs[i]-scs[i-1]))
                varX.append(inverted_frame_rate[i-1]*((x[i]-mx)**2))
                varY.append(inverted_frame_rate[i-1]*((y[i]-my)**2))
                varZ.append(inverted_frame_rate[i-1]*((z[i]-mz)**2))
            sumlist = np.array([sum(varX),sum(varY),sum(varZ)])
            normalizer = sum(inverted_frame_rate)
            instability.append(sumlist/normalizer)

        weighted_instability_matrix = instability*weights

        inst = np.sum(weighted_instability_matrix)

        # print(normalizer)
        # print(sumlist)
        # print joint stability-l
        os.chdir(output_dir)

        for k in range(len(instability)):
            metric = joint_types[k] + '_Stability-l'
            element = instability[k]
            row_out = [subjID,aasanaID,metric,element]
            with open('OUTPUT.csv','a') as csvFile:
                csv_writer = csv.writer(csvFile)
                csv_writer.writerow(row_out)

        row1 = [subjID,aasanaID,'Stability-l',inst]
        
        with open('OUTPUT.csv','a') as csvFile:
            csv_writer = csv.writer(csvFile)
            csv_writer.writerow(row1)
        print(row1)
        os.chdir(directory)

        instability1 = []
        for i in range(25):
            any_joint = jointwise[i]
            hrs = []
            mns = []
            scs = []
            x = []
            y = []
            z = []
            varX = []
            varY = []
            varZ = []
            inverted_frame_rate = []
            for row in any_joint[begin_right+10:end_right-10]:
                hours, minutes, seconds = row[1].split(':')
                hours, minutes, seconds = np.float64(hours), np.float64(minutes), np.float64(seconds) 
                hrs.append(hours)
                mns.append(minutes)
                scs.append(seconds)
                x.append(np.float64(row[7]))
                y.append(np.float64(row[8]))
                z.append(np.float64(row[9]))
            mx,my,mz = np.mean(x),np.mean(y),np.mean(z)
            for i in range(1,len(x)):
                inverted_frame_rate.append(3600*(hrs[i]-hrs[i-1])+60*(mns[i]-mns[i-1])+(scs[i]-scs[i-1]))
                varX.append(inverted_frame_rate[i-1]*((x[i]-mx)**2))
                varY.append(inverted_frame_rate[i-1]*((y[i]-my)**2))
                varZ.append(inverted_frame_rate[i-1]*((z[i]-mz)**2))
            sumlist = np.array([sum(varX),sum(varY),sum(varZ)])
            normalizer = sum(inverted_frame_rate)
            instability1.append(sumlist/normalizer)

        weighted_instability1_matrix = instability1*weights

        inst1 = np.sum(weighted_instability1_matrix)

        # print(normalizer)
        # print(sumlist)
        os.chdir(output_dir)

        for k in range(len(instability1)):
            metric = joint_types[k] + '_Stability-r'
            element = instability1[k]
            row_out = [subjID,aasanaID,metric,element]
            with open('OUTPUT.csv','a') as csvFile:
                csv_writer = csv.writer(csvFile)
                csv_writer.writerow(row_out)

        row1 = [subjID,aasanaID,'Stability-r',inst1]
        
        with open('OUTPUT.csv','a') as csvFile:
            csv_writer = csv.writer(csvFile)
            csv_writer.writerow(row1)
        print(row1)
        os.chdir(directory)

    extract_classification_stability(subjectID,clf.Type.unilateral,'Type_unilateral')
    extract_classification_stability(subjectID,clf.Type.bilateral,'Type_bilateral')
    extract_classification_stability(subjectID,clf.Type.horizontal,'Type_horizontal')
    extract_classification_stability(subjectID,clf.Category.non_balancing,'Category_nonbalancing')
    extract_classification_stability(subjectID,clf.Category.balancing,'Category_balancing')

os.chdir(output_dir)
print('~Fin')